apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":"2022-09-18T00:06:49Z","labels":{"app":"voting-app","component":"results-app","run":"results-app"},"name":"results-app","namespace":"default","resourceVersion":"189275","uid":"5148d0a5-03e5-4aba-8018-325a6a97b12a"},"spec":{"containers":[{"image":"dockersamples/examplevotingapp_result","imagePullPolicy":"Always","name":"results-app","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"kube-api-access-cv4zp","readOnly":true}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"nodeName":"docker-desktop","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-cv4zp","projected":{"defaultMode":420,"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"items":[{"key":"ca.crt","path":"ca.crt"}],"name":"kube-root-ca.crt"}},{"downwardAPI":{"items":[{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"},"path":"namespace"}]}}]}}]},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2022-09-18T00:06:49Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2022-09-18T00:06:53Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2022-09-18T00:06:53Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2022-09-18T00:06:49Z","status":"True","type":"PodScheduled"}],"containerStatuses":[{"containerID":"docker://2247e4b4056511e37ba8ede345304024385766901ab80493f291596b9d3df0eb","image":"dockersamples/examplevotingapp_result:latest","imageID":"docker-pullable://dockersamples/examplevotingapp_result@sha256:96e33cfd07d422aac24158b8f536114d8636092b39c97b52935d92e81d78d761","lastState":{},"name":"results-app","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2022-09-18T00:06:53Z"}}}],"hostIP":"192.168.65.4","phase":"Running","podIP":"10.1.0.45","podIPs":[{"ip":"10.1.0.45"}],"qosClass":"BestEffort","startTime":"2022-09-18T00:06:49Z"}}
  creationTimestamp: "2022-09-18T00:06:49Z"
  labels:
    app: voting-app
    component: results-app
    run: results-app
  name: results-app
  namespace: default
  resourceVersion: "189394"
  uid: 5148d0a5-03e5-4aba-8018-325a6a97b12a
spec:
  containers:
  - image: dockersamples/examplevotingapp_result
    imagePullPolicy: Always
    name: results-app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cv4zp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-cv4zp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-18T00:06:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-18T00:06:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-18T00:06:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-18T00:06:49Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2247e4b4056511e37ba8ede345304024385766901ab80493f291596b9d3df0eb
    image: dockersamples/examplevotingapp_result:latest
    imageID: docker-pullable://dockersamples/examplevotingapp_result@sha256:96e33cfd07d422aac24158b8f536114d8636092b39c97b52935d92e81d78d761
    lastState: {}
    name: results-app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-09-18T00:06:53Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.45
  podIPs:
  - ip: 10.1.0.45
  qosClass: BestEffort
  startTime: "2022-09-18T00:06:49Z"
---
apiVersion: v1
kind: Service
metadata:
  name: results-app
spec:
  type: NodePort
  selector:
    app: voting-app
    component: results-app
  ports:
    - port: 80