apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-09-17T23:59:00Z"
  labels:
    run: voting-app
    app: voting-app
    component: voting-app
  name: voting-app
  namespace: default
  resourceVersion: "188669"
  uid: 506b9d67-fde8-447b-9ea8-f58661c7a20e
spec:
  containers:
  - image: dockersamples/examplevotingapp_vote:before
    imagePullPolicy: IfNotPresent
    name: voting-app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sh4k5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-sh4k5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-17T23:59:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-17T23:59:03Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-17T23:59:03Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-17T23:59:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cd9681af4251e38339597887afc2e5506a8e80aa04df42c84bc755d8bb2120e7
    image: dockersamples/examplevotingapp_vote:before
    imageID: docker-pullable://dockersamples/examplevotingapp_vote@sha256:8e64b18b2c87de902f2b72321c89b4af4e2b942d76d0b772532ff27ec4c6ebf6
    lastState: {}
    name: voting-app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-09-17T23:59:03Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.44
  podIPs:
  - ip: 10.1.0.44
  qosClass: BestEffort
  startTime: "2022-09-17T23:59:00Z"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
    component: voting-app
  ports:
    - port: 80